enterprise_pmg/views/admin.py
from flask import *
from flask_mail import *
from enterprise_pmg import app, mail
from enterprise_pmg.model import Admin
from enterprise_pmg.Forms import AdminForms
#from APIs import EnterForms
#from  APIs import EnterpriseAPI
import os
from werkzeug.utils import secure_filename
from PIL import Image


mod = Blueprint('admin', __name__, url_prefix = '/admin')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@mod.route('/')
def admin():
    return render_template('AdminTemplates/admin.html', username = session['username'], role = session['role'], image_file = session['ProPic'])

@mod.route('/users', methods = ['GET','POST'])
def users():
    AllUsers = Admin.Users.GetAllUsers()
    form = AdminForms.CreateUser(request.form)
    return render_template('AdminTemplates/users.html', username = session['username'], 
                            role = session['role'], image_file = session['ProPic'], 
                            allusers = AllUsers, form = form)

@mod.route('/CreateNewUser', methods = ['GET','POST'])
def CreateNewUser():
    form = AdminForms.CreateUser(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                NewUser = Admin.Users(request.form['firstname'],
                                      request.form['lastname'],
                                      request.form['position'],
                                      request.form['department'],
                                      request.form['email'],
                                      request.form['phone1'],
                                      request.form.getlist('role-check'),
                                      'Active', 'default.png')
                usrname = NewUser.UserName
                pswd, hashpass = Admin.Users.createpassword(usrname)
                msg = Message('New Enterprise Account', recipients = [str(request.form['email'])])
                msg.body = "Dear {}, \n Thank you for using Enterprise. please note that your username is: {} and your password is {}. \n It is highly recommended that you change your password as soon as possible. \n Thank you for using Enterprise.".format(str(request.form['firstname']), str(usrname), str(pswd)) 
                mail.send(msg)
                flash('New user was successfully created...', category = 'success')
                return redirect(url_for('admin.users'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.users'))           
    return redirect(url_for('admin.users'))

@mod.route('/UpdateUser/<uid>', methods = ['GET','POST'])
def UpdateUser(uid):
    form = AdminForms.CreateUser(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.Users.UPDATE_ONE_USER(uid,
                                            request.form['firstname'],
                                      request.form['lastname'],
                                      request.form['position'],
                                      request.form['department'],
                                      request.form['email'],
                                      request.form['phone1'],
                                      request.form.getlist('role-check'),
                                      request.form['status'], request.form['profilepic'])
                flash('User was successfully updated...', category = 'success')
                return redirect(url_for('admin.users'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.users'))
    return redirect(url_for('admin.users'))

@mod.route('/ResetPassword/<uid>')
def ResetPassword(uid):
    try:
        firstname, pswd, email = Admin.Users.RESET_PASSWORD(uid)
        msg = Message('Password reset', recipients = [str(email)])
        msg.body = "Dear {}, \n Thank you for using Enterprise. please note that your  password was reset to {}. \n It is highly recommended that you change your password as soon as possible. \n Thank you for using Enterprise.".format(str(firstname), str(pswd)) 
        mail.send(msg)
        flash('User password was successfully reset...', category = 'success')
        return redirect(url_for('admin.users'))
    except Exception as e:
        flash(str(e), category = 'fail')
        return redirect(url_for('admin.users'))
    return redirect(url_for('admin.users'))

@mod.route('/StakeHolders', methods = ['GET','POST'])
def StakeHolders():
    form = AdminForms.StakeHolderForm(request.form)
    AllStakeHolders = Admin.StakeHolder.GetAllStakeHolders()
    return render_template('AdminTemplates/stakeholders.html', username = session['username'], role = session['role'], image_file = session['ProPic'],
                            form = form, AllStakeHolders = AllStakeHolders)


@mod.route('/CreateNewStakeHolder', methods = ['GET','POST'])
def CreateNewStakeHolder():
    form = AdminForms.StakeHolderForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.StakeHolder(request.form['StakeHolderName'],
                                    request.form['StakeHolderType'],
                                    request.form['StakeHolderAddress'],
                                    request.form['StakeHolderContact'],
                                    request.form['StakeHolderEmail'],
                                    request.form['StakeHolderStatus'],
                                    request.form['StakeHolderDescription']) 
                flash('New Stake Holder was successfully created...', category = 'success')
                return redirect(url_for('admin.StakeHolders'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.StakeHolders'))
    return redirect(url_for('admin.StakeHolders'))

@mod.route('/EditStakeHolder/<sid>', methods = ['GET','POST'])
def EditStakeHolder(sid):
    form = AdminForms.StakeHolderForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.StakeHolder.UpdateStakeHolder(sid, request.form['StakeHolderName'],
                                    request.form['StakeHolderType'],
                                    request.form['StakeHolderAddress'],
                                    request.form['StakeHolderContact'],
                                    request.form['StakeHolderEmail'],
                                    request.form['StakeHolderStatus'],
                                    request.form['StakeHolderDescription'])
                flash('Stake Holder information were successfully updated...', category = 'success')
                return redirect(url_for('admin.StakeHolders')) 
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.StakeHolders'))
    return redirect(url_for('admin.StakeHolders'))

@mod.route('/CompanyProfile', methods = ['GET','POST'])
def CompanyProfile():
    form = AdminForms.CompanyProfileForm(request.form)
    cmp = Admin.CompanyProfile.GetCompanyByID(1)
    filename = cmp.Logo
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                file = request.files['Logo']
                if file and allowed_file(file.filename):
                    filename = secure_filename(file.filename)
                    out_size = (125,125)
                    i = Image.open(file)
                    i.thumbnail(out_size)
                    i.save(os.path.join(app.root_path , 'static/images/company', filename))
                Admin.CompanyProfile.UpdateCompanyProfile(
                    request.form['CompanyName'],
                    request.form['Address'],
                    request.form['Phone_1'],
                    request.form['Phone_2'],
                    request.form['Email'],
                    request.form['POBox'],
                    request.form['Registration'],
                    request.form['Description'],
                    filename
                )
                flash('Company profile was updated successfully...', category = 'success')
                return redirect(url_for('admin.CompanyProfile'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.CompanyProfile'))
    return render_template('AdminTemplates/company.html', username = session['username'], role = session['role'], image_file = session['ProPic'],
                            form = form)

enterprise_pmg/templates/AdminTemplates/admin.html
{% extends 'LoginTemplates/layout.html'%}
{% block content%}
<div class="vertical-menu">
  <h3>Administration</h3>
 <a href = "{{url_for('admin.users')}}">Users</a>
 <a href = "{{url_for('admin.StakeHolders')}}">Stake Holders</a>
 <a href = "{{url_for('admin.CompanyProfile')}}">Company/Organization Profile</a>
</div>

  {% block adminpage%}
  {% endblock %}

{% endblock %}

enterprise_pmg/templates/AdminTemplates/company.html
{% extends 'AdminTemplates/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
    <form method = 'POST' style = 'margin-top: 2%; box-shadow: 5px 10px 20px rgb(155, 154, 154);' enctype = "multipart/form-data">
        <h3 id = 'title'> <img id = 'Logo-circle' class = 'big-circle' />Company Profile</h3>
        <div class = 'fields' style =  'margin-top: 8%;'>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            {{render_field(form.CompanyName)}}
            {{render_field(form.Address)}}
            {{render_field(form.Phone_1)}}
            {{render_field(form.Phone_2)}}
            {{render_field(form.Email)}}
            {{render_field(form.POBox)}}
            {{render_field(form.Registration)}}
            {{render_field(form.Description)}}
            {{render_field(form.Logo)}}
        </div>
        <div class = 'submission'>
            {{form.submit(class = 'btn-active')}}
        </div>
        <div class = 'flashes'>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class = "{{category}}">
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            </div>
    </form>
</div>
<script>
    $(document).ready(function(){
        $.getJSON('/API/Admin/GetCompanyByID/1', function(data){
            $('#CompanyName').val(data.CompanyName);
            $('#Address').val(data.Address);
            $('#Phone_1').val(data.Phone_1);
            $('#Phone_2').val(data.Phone_2);
            $('#Email').val(data.Email);
            $('#POBox').val(data.POBox);
            $('#Registration').val(data.Registration);
            $('#Description').val(data.Description);
            $('#Logo').val(data.logo);
            $('#Logo-circle').attr('src', '/static/images/company/' + data.Logo);
        });
    });
</script>
{% endblock %}

enterprise_pmg/templates/AdminTemplates/stakeholders.html
{% extends 'AdminTemplates/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
    <button id = 'add-user' class = 'btn-active' style = 'float: left; width: 200px;'>Create New Stake Holder</button>
    <input type = 'text' style = 'border: solid rgb(0,0,100); border-width: 1px; border-radius: 3px; margin: 5px; float: left;box-shadow: 1px 1px 2px rgb(200,200,200);' placeholder = 'Search' id = 'srch' />
    <table>
        <thead>
            <tr>
                <th>ID:</th>
                <th>Name:</th>
                <th>Type:</th>
                <th>Contact:</th>
                <th>Email:</th>
                <th>Status:</th>
                <th>Edit:</th>   
            </tr>
        </thead>
        {% for s in AllStakeHolders.items %}
            <tr class = 'table-row {{s.SHStatus}}'>
                <td>{{s.SHID}}</td>
                <td>{{s.SHName}}</td>
                <td>{{s.SHType}}</td>
                <td>{{s.SHContact}}</td>
                <td>{{s.SHEmail}}</td>
                <td>{{s.SHStatus}}</td>
                <td><a href = "#" class = 'EditUser' id = "{{s.SHID}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = 'height:25px; width: 25px;'/></a></td>
            </tr> 
        {% endfor %}
        </tbody>
    </table>
    <div class = 'paginator' style = 'margin-top: 20px;'>
      {% for page_num in AllStakeHolders.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
        {% if page_num %}
          {% if AllStakeHolders.page == page_num %}
            <a href = "{{url_for('admin.StakeHolders', page = page_num)}}" class = 'pg-inline'>{{page_num}}</a>
          {% else %}
            <a href = "{{url_for('admin.StakeHolders', page = page_num)}}" class = 'pg-outline'>{{page_num}}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
      {% endfor %}
    </div>
    <div class = 'flashes'>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class = "{{category}}">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
</div>
<div id="myModal" class="modal">
    <div class="modal-content" style = 'background-color:rgba(126, 126, 126, 0); border: none;'>
        <form method = 'POST' action = "{{url_for('admin.CreateNewStakeHolder')}}" style = 'width:100%;' id = 'CreateUserForm'>
            <h3>Create New Stake Holder <span class="close">&times;</span></h3>
            <div class = 'fields'>
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              {{ render_field(form.StakeHolderName) }}
              {{ render_field(form.StakeHolderType) }}
              {{ render_field(form.StakeHolderAddress)}}
              {{ render_field(form.StakeHolderContact)}}
              {{ render_field(form.StakeHolderEmail)}}
              {{ render_field(form.StakeHolderStatus)}}
              {{ render_field(form.StakeHolderDescription) }}
            </div>
            <div class = 'submission'>
              {{form.submit(class = 'btn-active')}}
            </div>
          </form>
    </div>
</div>


<div id="myModal_1" class="modal">
  <div class="modal-content" style = 'background-color:rgba(126, 126, 126, 0); border: none;'>
      <form method = 'POST' id = 'EditUserForm' style = 'width:100%;'>
          <h3 id = 'title' >Edit Stake Holder<span class='close'>&times;</span> </h3>
          <div class = 'fields'>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class = 'row'>
              <div class = 'col-a'>
                <label> ID: </label>
              </div>
              <div class = 'col-b'>
                <input type = 'text' id = 'id' disabled/> 
              </div>
            </div>
            {{ render_field(form.StakeHolderName, id = 'sname') }}
            {{ render_field(form.StakeHolderType, id = 'stype') }}
            {{ render_field(form.StakeHolderAddress, id = 'saddress')}}
            {{ render_field(form.StakeHolderContact, id = 'scontact')}}
            {{ render_field(form.StakeHolderEmail, id = 'semail')}}
            {{ render_field(form.StakeHolderStatus, id = 'sstatus')}}
            {{ render_field(form.StakeHolderDescription, id = 'sdescription') }}
          </div>
          <div class = 'submission'>
            {{form.submit(class = 'btn-active')}}
          </div>
        </form>
  </div>
</div>
  
<script>
    $(document).ready(function(){

        var uid;

        $('#add-user').click(function(){
            $('#myModal').show();
        });
        $('.close').click(function(){
            $('.modal').hide();
        });
        $('#select_all').click(function(){
            $('.appr_check').prop('checked', this.checked);
        });
        $('#select_all_roles').click(function(){
            $('.role_check').prop('checked', this.checked);
        });

        $('#select_all_roles_edit').click(function(){
            $('.role_check_edit').prop('checked', this.checked);
        });

        $('.EditUser').on('click',function(){
          uid = $(this).attr('id');
          $('#myModal_1').show();
          $.getJSON('/API/Admin/GetStakeHolderByID/' + $(this).attr('id'), function(data){
            //alert(data.UserName);
            $('#id').val(data.SHID);
            $('#sname').val(data.SHName);
            $('#stype').prepend("<option value = '"+ data.SHType+"' selected hidden>"+ data.SHType +"</option>");
            $('#saddress').val(data.SHAddress);
            $('#scontact').val(data.SHContact);
            $('#semail').val(data.SHEmail);
            $('#sstatus').prepend("<option value = '" + data.SHStatus + "' selected hidden>"+ data.SHStatus +"</option>");
            $('#sdescription').val(data.SHDescription);
          });
          $('#EditUserForm').attr('action', "/admin/EditStakeHolder/" + uid);
        });
    });
</script>

{% endblock %}

enterprise_pmg/templates/AdminTemplates/users.html
{% extends 'AdminTemplates/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
    <button id = 'add-user' class = 'btn-active' style = 'float: left; width: 150px;'>Create New User</button>
    <input type = 'text' style = 'border: solid rgb(0,0,100); border-width: 1px; border-radius: 3px; margin: 5px; float: left;box-shadow: 1px 1px 2px rgb(200,200,200);' placeholder = 'Search' id = 'srch' />
    <table>
        <thead>
            <tr>
                <th>User ID:</th>
                <th>First Name:</th>
                <th>Last Name:</th>
                <th>Username:</th>
                <th>Position:</th>
                <th>Department:</th>
                <th>Email:</th>
                <th>Phone:</th>
                <th>Role:</th>
                <th>Status:</th>
                <th>Edit:</th>
                <th>Reset Password:</th>
            </tr>
        </thead>
        {% for u in allusers.items %}
          {% if u.UserName != 'admin' %}
            <tr class = 'table-row {{u.Status}}'>
                <td>{{u.UserId}}</td>
                <td>{{u.FirstName}}</td>
                <td>{{u.LastName}}</td>
                <td>{{u.UserName}}</td>
                <td>{{u.Position}}</td>
                <td>{{u.Department}}</td>
                <td>{{u.Email}}</td>
                <td>{{u.Phone}}</td>
                <td>{%for r in u.Role%}{{r}}, {% endfor %}</td>
                <td>{{u.Status}}</td>
                <td><a href = "#" class = 'EditUser' id = "{{u.UserId}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = 'height:25px; width: 25px;'/></a></td>
                <td><a href = "{{url_for('admin.ResetPassword', uid = u.UserId)}}"><img src = "{{url_for('static', filename = 'images/reset_password.png')}}" style = 'height:25px; width: 25px;'/></a></td>
            </tr>
          {% endif %}  
        {% endfor %}
        </tbody>
    </table>
    <div class = 'paginator' style = 'margin-top: 20px;'>
      {% for page_num in allusers.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
        {% if page_num %}
          {% if allusers.page == page_num %}
            <a href = "{{url_for('admin.users', page = page_num)}}" class = 'pg-inline'>{{page_num}}</a>
          {% else %}
            <a href = "{{url_for('admin.users', page = page_num)}}" class = 'pg-outline'>{{page_num}}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
      {% endfor %}
    </div>
    <div class = 'flashes'>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class = "{{category}}">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
</div>
<div id="myModal" class="modal">
    <div class="modal-content" style = 'background-color:rgba(126, 126, 126, 0); border: none;'>
        <form method = 'POST' action = "{{url_for('admin.CreateNewUser')}}" style = 'width:100%;' id = 'CreateUserForm'>
            <h3>Create New User <span class="close">&times;</span></h3>
            <div class = 'fields'>
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              {{ render_field(form.firstname) }}
              {{ render_field(form.lastname) }}
              {{ render_field(form.position)}}
              {{ render_field(form.department)}}
              {{ render_field(form.email)}}
              {{ render_field(form.phone1)}}
              <div class = 'row'>
                <div class = 'col-a'>
                  <label>Roles:</label>
                </div>
                <div class = 'col-b'>
                  <table>
                    <tr>
                      <th><input type = 'Checkbox' id = 'select_all_roles' />Select All</th>
                      <th>Roles:</th>
                    </tr>
                    <tr>
                      <td><input type = 'Checkbox' value = 'Admin' name = 'role-check' class = 'role_check'/></td>
                      <td>Administration</td>
                    </tr>
                    <tr>
                      <td><input type = 'Checkbox' value = 'Projects' name = 'role-check' class = 'role_check'/></td>
                      <td>Projects</td>
                    </tr>
                    <tr>
                      <td><input type = 'Checkbox' value = 'Tasks' name = 'role-check' class = 'role_check'/></td>
                      <td>Projects/Tasks</td>
                    </tr>
                    <tr>
                      <td><input type = 'Checkbox' value = 'Budget' name = 'role-check' class = 'role_check'/></td>
                      <td>Projects/Budget</td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class = 'submission'>
              {{form.submit(class = 'btn-active')}}
            </div>
          </form>
    </div>
</div>


<div id="myModal_1" class="modal">
  <div class="modal-content" style = 'background-color:rgba(126, 126, 126, 0); border: none;'>
      <form method = 'POST' id = 'EditUserForm' style = 'width:100%;'>
          <h3 id = 'title' > <img id = 'userpic' class = 'big-circle' />Edit User<span class='close'>&times;</span> </h3>
          <div class = 'fields' style = 'margin-top: 8%;'>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class = 'row'>
              <div class = 'col-a'>
                <label>User ID: </label>
              </div>
              <div class = 'col-b'>
                <input type = 'text' id = 'uid' disabled/> 
              </div>
            </div>
            <div class = 'row'>
              <div class = 'col-a'>
                <label>Username: </label>
              </div>
              <div class = 'col-b'>
                <input type = 'text' id = 'uname' disabled/> 
              </div>
            </div>
            {{ render_field(form.firstname, id = 'fname') }}
            {{ render_field(form.lastname, id = 'lname') }}
            {{ render_field(form.position, id = 'pos')}}
            {{ render_field(form.department, id = 'dept')}}
            {{ render_field(form.email, id = 'e_mail')}}
            {{ render_field(form.phone1, id = 'phone')}}
            <div class = 'row'>
              <div class = 'col-a'>
                <label>Roles:</label>
              </div>
              <div class = 'col-b'>
                <table>
                  <tr>
                    <th><input type = 'Checkbox' id = 'select_all_roles_edit' />Select All</th>
                    <th>Roles:</th>
                  </tr>
                  <tr>
                    <td><input type = 'Checkbox' value = 'Admin' name = 'role-check' class = 'role_check_edit' id = 'admincheck'/></td>
                    <td>Administration</td>
                  </tr>
                  <tr>
                    <td><input type = 'Checkbox' value = 'Projects' name = 'role-check' class = 'role_check_edit' id = 'projectcheck'/></td>
                    <td>Projects</td>
                  </tr>
                  <tr>
                    <td><input type = 'Checkbox' value = 'Tasks' name = 'role-check' class = 'role_check_edit' id = 'taskcheck'/></td>
                    <td>Projects/Tasks</td>
                  </tr>
                  <tr>
                    <td><input type = 'Checkbox' value = 'Budget' name = 'role-check' class = 'role_check_edit' id = 'budgetcheck'/></td>
                    <td>Projects/Budget</td>
                  </tr>
                </table>
              </div>
            </div>
            <div class = 'row'>
              <div class = 'col-a'>
                <label>Status: </label>
              </div>
              <div class = 'col-b'>
                <select name = 'status' id = 'status'>
                  <option value = 'Active'>Active</option>
                  <option value = 'Inactive'>Inactive</option>
                </select>
              </div>
            </div>
            <input type = 'text' id = 'profilepic' name = 'profilepic' hidden />
          </div>
          <div class = 'submission'>
            {{form.submit(class = 'btn-active')}}
          </div>
        </form>
  </div>
</div>
  
<script>
    $(document).ready(function(){

        var uid;

        $('#add-user').click(function(){
            $('#myModal').show();
        });
        $('.close').click(function(){
            $('.modal').hide();
        });
        $('#select_all').click(function(){
            $('.appr_check').prop('checked', this.checked);
        });
        $('#select_all_roles').click(function(){
            $('.role_check').prop('checked', this.checked);
        });

        $('#select_all_roles_edit').click(function(){
            $('.role_check_edit').prop('checked', this.checked);
        });

        $('.EditUser').on('click',function(){
          uid = $(this).attr('id');
          $('#myModal_1').show();
          $.getJSON('/API/Admin/GetUserByID/' + $(this).attr('id'), function(data){
            //alert(data.UserName);
            $('#uid').val(data.UserId);
            $('#uname').val(data.UserName);
            $('#fname').val(data.FirstName);
            $('#lname').val(data.LastName);
            $('#pos').val(data.Position);
            $('#dept').val(data.Department);
            $('#e_mail').val(data.Email);
            $('#phone').val(data.Phone);
            $('#status').prepend("<option value = '"+data.Status+"' selected hidden>"+data.Status+"</option>" );
            $('#profilepic').val(data.ProfilePic);
            $('#userpic').attr('src' , '/static/images/users/' + data.ProfilePic);
            $.each(data.Role, function(key, val){
                if(val === 'Admin'){$('#admincheck').attr('checked', 'true');}
                if(val === 'Projects'){$('#projectcheck').attr('checked', 'true');}
                if(val === 'Tasks'){$('#taskcheck').attr('checked', 'true');}
                if(val === 'Budget'){$('#budgetcheck').attr('checked', 'true');}
            });
          });
          $('#EditUserForm').attr('action', "/admin/UpdateUser/" + uid);
        });
    });
</script>

{% endblock %}