enterprise_pmg/views/projects.py
from flask import *
from flask_mail import *
from enterprise_pmg import app, mail
from enterprise_pmg.model import Projects, Admin
from enterprise_pmg.Forms import ProjectForms
import os
from werkzeug.utils import secure_filename
import datetime
from PIL import Image

mod = Blueprint('projects', __name__, url_prefix = '/projects')

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def allowed_document(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() not in ALLOWED_EXTENSIONS

def CheckManagers(ManagersList):
    allunames = Admin.Users.GetAllUserNames()
    for m in ManagersList:
        if m not in allunames:
            return '{} is not included as a user'.format(m)
            break
    return None

def CheckStakeHolders(stakeholderslist):
    allnames = Admin.StakeHolder.GetStakeHoldersList()
    for s in stakeholderslist:
        if s not in allnames:
            return 'Stakeholder {} is not identified.'.format(s)
            break
    return None

def GetProjectImages(code):
    return os.listdir(app.root_path + "/static/projects/{}/images".format(code))

def GetProjectDocs(code):
    return os.listdir(app.root_path + "/static/projects/{}/documents".format(code))
    

def CreateProjectDirectory(code):
    os.mkdir(app.root_path + "/static/projects/{}".format(code))
    os.mkdir(app.root_path + "/static/projects/{}/documents".format(code))
    os.mkdir(app.root_path + "/static/projects/{}/images".format(code))

    
@mod.route('/')
def projects():
    return redirect(url_for('projects.allprojects'))

@mod.route('/allprojects', methods = ['Get','POST'])
def allprojects():
    projs = Projects.Project.GetAllProjects()
    form = ProjectForms.ProjectForm(request.form)
    users = Admin.Users.SELECT_ALL()
    shs = Admin.StakeHolder.GET_ALL_STAKEHOLDERS()
    return render_template('ProjectTemplates/projects_home.html', username = session['username'], role = session['role'], image_file = session['ProPic'],
                            form = form,
                            allprojects = projs,
                            users = users,
                            shs = shs)

@mod.route('/CreateProject', methods = ['GET','POST'])
def CreateProject():
    form = ProjectForms.ProjectForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                managers = request.form['Managers'].split(',')
                stakeholders = request.form['StakeHolders'].split(',')
                mancheck = CheckManagers(managers)
                shcheck = CheckStakeHolders(stakeholders)
                if mancheck:
                    flash(mancheck, category = 'fail')
                    return redirect(url_for('projects.allprojects'))
                elif shcheck:
                    flash(shcheck, category = 'fail')
                    return redirect(url_for('projects.allprojects'))
                else:
                    NewProject = Projects.Project(request.form['ProjectCode'],
                                                request.form['ProjectStartDate'], 
                                                request.form['ProjectEndDate'], 
                                                request.form['Location'],
                                                request.form['FundingSource'],
                                                request.form['TotalBudget'],
                                                request.form['Currency'],
                                                managers, stakeholders,
                                                request.form['Description'], request.form['Log'])
                    CreateProjectDirectory(request.form['ProjectCode'])
                    flash('New project was successfully created...', category = 'success')
                    return redirect(url_for('projects.allprojects'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('projects.allprojects'))
    return redirect(url_for('projects.allprojects'))

@mod.route('/UpdateProject/<code>', methods = ['GET','POST'])
def UpdateProject(code):
    form = ProjectForms.ProjectForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                if request.form['Managers'] == None or request.form['ProjectStartDate'] == None or request.form['ProjectEndDate'] == None:
                    flash('Missing required values, please recheck...', category = 'fail')
                    return redirect(url_for('projects.allprojects'))
                else:
                    managers = request.form['Managers'].split(',')
                    stakeholders = request.form['StakeHolders'].split(',')
                    mancheck = CheckManagers(managers)
                    shcheck = CheckStakeHolders(stakeholders)
                    if mancheck:
                        flash(mancheck, category = 'fail')
                        return redirect(url_for('projects.allprojects'))
                    elif shcheck:
                        flash(shcheck, category = 'fail')
                        return redirect(url_for('projects.allprojects'))
                    else:
                        Projects.Project.UpdateProjectByCode(code,
                                                request.form['ProjectStartDate'],
                                                request.form['ProjectEndDate'],
                                                request.form['Location'],
                                                request.form['FundingSource'],
                                                request.form['TotalBudget'],
                                                request.form['Currency'],
                                                managers, stakeholders,
                                                request.form['Description'],
                                                request.form['Log'])
                        flash('Project {} was successfully updated'.format(code), category = 'success')
                        return redirect(url_for('projects.allprojects'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('projects.allprojects'))
    return redirect(url_for('projects.allprojects'))

@mod.route('/project/<code>', methods = ['GET','POST'])
def project(code):
    imgs = GetProjectImages(code)
    docs = GetProjectDocs(code)
    TaskForm = ProjectForms.TaskForm(request.form)
    return render_template('ProjectTemplates/project.html', username = session['username'], role = session['role'], image_file = session['ProPic'], code = code,
    imgs = imgs, docs = docs, 
    TaskForm = TaskForm)

@mod.route('/uploadfiles/<code>', methods = ['Get','POST'])
def UploadFiles(code):
    if request.method == 'POST':
        try:
            files = request.files.getlist('file')
            for file in files:
                if file and allowed_document(file.filename):
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(app.root_path , 'static/projects/{}/documents'.format(code), filename))
            return redirect(url_for('projects.project', code = code))
        except Exception as e:
            flash(str(e), category = 'fail')
            return redirect(url_for('projects.project', code = code))
    return redirect(url_for('projects.project', code = code))

@mod.route('/removefile/<code>/<file>')
def RemoveFile(code, file):
    os.remove(app.root_path + '/static/projects/{}/documents/{}'.format(code, file))
    return redirect(url_for('projects.project', code = code))

@mod.route('/removeimage/<code>/<file>')
def RemoveImage(code, file):
    os.remove(app.root_path + '/static/projects/{}/images/{}'.format(code, file))
    return redirect(url_for('projects.project', code = code))


@mod.route('/uploadimages/<code>', methods = ['GET','POST'])
def UploadImages(code):
    if request.method == 'POST':
        try:
            files = request.files.getlist('file')
            for file in files:
                if file and allowed_file(file.filename):
                    filename = secure_filename(file.filename)
                    file.save(os.path.join(app.root_path , 'static/projects/{}/images'.format(code), filename))
            return redirect(url_for('projects.project', code = code))
        except Exception as e:
            flash(str(e), category = 'fail')
            return redirect(url_for('projects.project', code = code))
    return redirect(url_for('projects.project', code = code))

enterprise_pmg/templates/ProjectTemplates/project.html
{% extends 'LoginTemplates/layout.html'%}
{% from 'renderfield.html' import render_field %}
{% block content%}
<script src = "{{url_for('static', filename = 'js/jquery/jQuery-Tags-Input-master/src/jquery.tagsinput.js')}}"></script>
<link rel = 'stylesheet' type = 'text/css' href = "{{url_for('static', filename = 'js/jquery/jQuery-Tags-Input-master/src/jquery.tagsinput.css')}}" /> 
<div class = 'actionpage' style = 'float: left; margin: 0px; padding: 0px;'>
    <div class="tab">
        <h3>{{code}}</h3>
        <button class="tablinks" onclick="openTab(event, 'Summary')" id="defaultOpen">Summary</button>
        {% if 'Tasks' in role %}<button class="tablinks" onclick="openTab(event, 'Tasks')">Tasks</button> {% endif %}
        {% if 'Budget' in role %}<button class="tablinks" onclick="openTab(event, 'Budget')">Budget</button>{% endif %}
        <button class="tablinks" onclick="openTab(event, 'Documents')">Documents</button>
      </div>
      
      <div id="Summary" class="tabcontent">
        <h3> Project Summary</h3>
        <p>Here comes the project Dashboard</p>
      </div>
      
      <div id="Tasks" class="tabcontent">
        <h3>Tasks</h3>
        <button id = 'add-task' class = 'btn-active' style = 'float: left; width: 150px;'>Create New Task</button>
        <input type = 'text' style = 'border: solid rgb(0,0,100); border-width: 1px; border-radius: 3px; margin: 5px; float: left;box-shadow: 1px 1px 2px rgb(200,200,200);' placeholder = 'Search' id = 'srch' /> 
      </div>
      
      <div id="Budget" class="tabcontent">
        <h3>Budget</h3>
        <p>Here comes the project budget.</p>
      </div> 
      
      <div id="Documents" class="tabcontent">
        <h3>Documents</h3>
        <div class = 'Documents-content'>
            <div id = "mytabs">
                <ul>
                  <li><a href = "#tabs-1">Documents</a></li>
                  <li><a href = "#tabs-2">Images</a></li>
                </ul>
              
                <div id="tabs-1" class="tabcontent-1">
                  <div>
                    <table style = 'margin: 10px; box-shadow: none; margin-bottom: 25px;'>
                      {% for d in docs %}
                        <tr>
                          <td><a href = "{{url_for('static', filename = 'projects/{}/documents/{}'.format(code, d))}}"> <img src = "{{url_for('static', filename = 'images/report.png')}}" style = 'height: 25px; width: 25px; margin-right: 25px;'/>{{d}}</a></td>
                          <td><a href = "{{url_for('projects.RemoveFile', code = code, file = d)}}"><img src = "{{url_for('static', filename = 'images/rmv.png')}}" style = 'height: 25px; width: 25px;'/></a></td>
                        </tr>
                      {% endfor %}
                    </table>
                  </div>
                  <div id = 'files-uploads' >
                    <form action="{{url_for('projects.UploadFiles', code = code)}}" class="dropzone" enctype="multipart/form-data">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    </form>
                  </div>
                </div>
                <div id="tabs-2" class="tabcontent-1">
                  <div style = 'margin-top: 15px; margin-bottom: 25px; '>
                    {% for i in imgs%}
                      <a href = "{{url_for('static', filename = 'projects/{}/images/{}'.format(code, i))}}" class = 'img-container' id = '{{i}}'><img src = "{{url_for('static', filename = 'projects/{}/images/{}'.format(code, i))}}" class = 'img-directory'/></a>
                      <span id = "rmv-{{i}}" ><a href = "{{url_for('projects.RemoveImage', code = code, file = i)}}"><img src = "{{url_for('static', filename = 'images/rmv.png')}}"  style = 'height: 25px; width: 25px; margin-left: -20px; background-color: rgb(150, 150, 150); border-radius: 40%; padding: 5px; box-shadow: 0px 2px 4px 0px rgba(177, 177, 177, 0.623); ' /></a></span>
                    {% endfor %}
                  </div>
                  <div id = 'images-uploads'>
                    <form action="{{url_for('projects.UploadImages', code = code)}}" class="dropzone" enctype="multipart/form-data">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    </form>
                  </div>
                </div>
              </div>
        </div>
      </div> 
</div>

<div id = 'create-task-modal' class = 'modal'>
  <div class = 'modal-content' style = 'background-color:rgba(126, 126, 126, 0); border: none;'>
    <form style = 'width:100%;'>
      <h3>Create New Task <span class="close" id  = 'close-task-creation'>&times;</span></h3>
      <div class = 'fields'>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        {{render_field(TaskForm.TaskPriority)}}
        {{render_field(TaskForm.TaskDescription)}}
        {{render_field(TaskForm.ExpectedStartDate)}}
        {{render_field(TaskForm.ExpectedEndDate)}}
        {{render_field(TaskForm.ActualStartDate)}}
        {{render_field(TaskForm.ActualEndDate)}}
        {{render_field(TaskForm.Location)}}

        <div class = 'row'>
          <div class = 'col-a'>
            <label>Assigned To:</label>
            <span style = 'float: right; margin-left: 10px;' class = 'search-managers' id = 'search-managers'><img src = "{{url_for('static', filename = 'images/search.png')}}" style = 'width: 25px; height: 25px;' /></span>
          </div>
          <div class = 'col-b'>
            {{TaskForm.AssignedTo}}
          </div>
        </div>

        {{render_field(TaskForm.Deliverables)}}

        <div class = 'row'>
          <div class = 'col-a'>
            <label>Depends On: </label>
          </div>
          <div class ='col-b'>
            <select id = 'selector'>
              <option>Select Task(s)</option>
            </select>
            <div class = 'select-what' id = 'task-creation-dependency'>
              <input type="checkbox" id="one" />First checkbox</br>
              <input type="checkbox" id="two" />Second checkbox</br>
              <input type="checkbox" id="three" />Third checkbox</br>
            </div>
          </div>
        </div>

        {{render_field(TaskForm.Status)}}
        {{render_field(TaskForm.Comments)}}
      </div>
      <div class = 'submission'>
        {{TaskForm.submit(class = 'btn-active')}}
      </div>
    </form>
  </div>
</div>
<style>
        * {box-sizing: border-box}

            /* Style the tab */
            .tab {
            float: left;
            width: 300px; /* Set a width if you like */
            height: 100%;
            position: fixed;
            background-color: #eee;
            padding: 5px;
            
            }

            /* Style the buttons that are used to open the tab content */
            .tab button {
            display: block;
            background-color: inherit;
            color: black;
            padding: 12px 16px;
            width: 100%;
            border: none;
            outline: none;
            text-align: left;
            cursor: pointer;
            transition: 0.3s;
            font-family: "Arial Black", Gadget, sans-serif;
            font-size: 16px;
            }

            /* Change background color of buttons on hover */
            .tab button:hover {
                background-color: white;
                color: rgb(0,0,100);
                font-weight: bold;
            }

            /* Create an active/current "tab button" class */
            .tab button.active {
                background-color: black;
                color: white;
                font-weight: bold;
            }

            /* Style the tab content */
            .tabcontent {
            /*float: right; */
            padding: 0px 12px;
            padding-top: 5px;
            border: 1px solid #ccc;
            width: 100%;
            height: 100%;
            margin-left: 300px;
            }

            .tabcontent-1 {
            margin-top: 10px;
            padding: 0px 12px;
            border: 1px solid rgb(0,0,100);
            width: 100%;
            height: auto;
            }
</style>
<script>
   function openTab(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
<script>
    $(document).ready(function(){
        $('#mytabs').tabs();
        $('#selector').click(function(){
          $('#task-creation-dependency').slideToggle();
        });
        $('#add-task').click(function(){
          $('#AssignedTo').tagsInput();
          $('#create-task-modal').show();
        });

        $('#close-task-creation').click(function(){
          $('#create-task-modal').hide();
        });
 
    });
</script>
{% endblock %}