enterprise_pmg/views/admin.py
from flask import *
from flask_mail import *
from enterprise_pmg import app, mail
from enterprise_pmg.model import Admin
from enterprise_pmg.Forms import AdminForms
#from APIs import EnterForms
#from  APIs import EnterpriseAPI
import os
from werkzeug.utils import secure_filename
from PIL import Image


mod = Blueprint('admin', __name__, url_prefix = '/admin')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@mod.route('/')
def admin():
    return render_template('AdminTemplates/admin.html', username = session['username'], role = session['role'], image_file = session['ProPic'])

@mod.route('/users', methods = ['GET','POST'])
def users():
    AllUsers = Admin.Users.GetAllUsers()
    form = AdminForms.CreateUser(request.form)
    return render_template('AdminTemplates/users.html', username = session['username'], 
                            role = session['role'], image_file = session['ProPic'], 
                            allusers = AllUsers, form = form)

@mod.route('/CreateNewUser', methods = ['GET','POST'])
def CreateNewUser():
    form = AdminForms.CreateUser(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                NewUser = Admin.Users(request.form['firstname'],
                                      request.form['lastname'],
                                      request.form['position'],
                                      request.form['department'],
                                      request.form['email'],
                                      request.form['phone1'],
                                      request.form.getlist('role-check'),
                                      'Active', 'default.png')
                usrname = NewUser.UserName
                pswd, hashpass = Admin.Users.createpassword(usrname)
                msg = Message('New Enterprise Account', recipients = [str(request.form['email'])])
                msg.body = "Dear {}, \n Thank you for using Enterprise. please note that your username is: {} and your password is {}. \n It is highly recommended that you change your password as soon as possible. \n Thank you for using Enterprise.".format(str(request.form['firstname']), str(usrname), str(pswd)) 
                mail.send(msg)
                flash('New user was successfully created...', category = 'success')
                return redirect(url_for('admin.users'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.users'))           
    return redirect(url_for('admin.users'))

@mod.route('/UpdateUser/<uid>', methods = ['GET','POST'])
def UpdateUser(uid):
    form = AdminForms.CreateUser(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.Users.UPDATE_ONE_USER(uid,
                                            request.form['firstname'],
                                      request.form['lastname'],
                                      request.form['position'],
                                      request.form['department'],
                                      request.form['email'],
                                      request.form['phone1'],
                                      request.form.getlist('role-check'),
                                      request.form['status'], request.form['profilepic'])
                flash('User was successfully updated...', category = 'success')
                return redirect(url_for('admin.users'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.users'))
    return redirect(url_for('admin.users'))

@mod.route('/ResetPassword/<uid>')
def ResetPassword(uid):
    try:
        firstname, pswd, email = Admin.Users.RESET_PASSWORD(uid)
        msg = Message('Password reset', recipients = [str(email)])
        msg.body = "Dear {}, \n Thank you for using Enterprise. please note that your  password was reset to {}. \n It is highly recommended that you change your password as soon as possible. \n Thank you for using Enterprise.".format(str(firstname), str(pswd)) 
        mail.send(msg)
        flash('User password was successfully reset...', category = 'success')
        return redirect(url_for('admin.users'))
    except Exception as e:
        flash(str(e), category = 'fail')
        return redirect(url_for('admin.users'))
    return redirect(url_for('admin.users'))

@mod.route('/StakeHolders', methods = ['GET','POST'])
def StakeHolders():
    form = AdminForms.StakeHolderForm(request.form)
    AllStakeHolders = Admin.StakeHolder.GetAllStakeHolders()
    return render_template('AdminTemplates/stakeholders.html', username = session['username'], role = session['role'], image_file = session['ProPic'],
                            form = form, AllStakeHolders = AllStakeHolders)


@mod.route('/CreateNewStakeHolder', methods = ['GET','POST'])
def CreateNewStakeHolder():
    form = AdminForms.StakeHolderForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.StakeHolder(request.form['StakeHolderName'],
                                    request.form['StakeHolderType'],
                                    request.form['StakeHolderAddress'],
                                    request.form['StakeHolderContact'],
                                    request.form['StakeHolderEmail'],
                                    request.form['StakeHolderStatus'],
                                    request.form['StakeHolderDescription']) 
                flash('New Stake Holder was successfully created...', category = 'success')
                return redirect(url_for('admin.StakeHolders'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.StakeHolders'))
    return redirect(url_for('admin.StakeHolders'))

@mod.route('/EditStakeHolder/<sid>', methods = ['GET','POST'])
def EditStakeHolder(sid):
    form = AdminForms.StakeHolderForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                Admin.StakeHolder.UpdateStakeHolder(sid, request.form['StakeHolderName'],
                                    request.form['StakeHolderType'],
                                    request.form['StakeHolderAddress'],
                                    request.form['StakeHolderContact'],
                                    request.form['StakeHolderEmail'],
                                    request.form['StakeHolderStatus'],
                                    request.form['StakeHolderDescription'])
                flash('Stake Holder information were successfully updated...', category = 'success')
                return redirect(url_for('admin.StakeHolders')) 
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.StakeHolders'))
    return redirect(url_for('admin.StakeHolders'))

@mod.route('/CompanyProfile', methods = ['GET','POST'])
def CompanyProfile():
    form = AdminForms.CompanyProfileForm(request.form)
    cmp = Admin.CompanyProfile.GetCompanyByID(1)
    filename = cmp.Logo
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                file = request.files['Logo']
                if file and allowed_file(file.filename):
                    filename = secure_filename(file.filename)
                    out_size = (125,125)
                    i = Image.open(file)
                    i.thumbnail(out_size)
                    i.save(os.path.join(app.root_path , 'static/images/company', filename))
                Admin.CompanyProfile.UpdateCompanyProfile(
                    request.form['CompanyName'],
                    request.form['Address'],
                    request.form['Phone_1'],
                    request.form['Phone_2'],
                    request.form['Email'],
                    request.form['POBox'],
                    request.form['Registration'],
                    request.form['Description'],
                    filename
                )
                flash('Company profile was updated successfully...', category = 'success')
                return redirect(url_for('admin.CompanyProfile'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('admin.CompanyProfile'))
    return render_template('AdminTemplates/company.html', username = session['username'], role = session['role'], image_file = session['ProPic'],
                            form = form)

enterprise_pmg/templates/LoginTemplates/change_forgot_password.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_login.css')}}" />
    <link rel="icon" href = "{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" /> 
  </head>
  <body>
    <form method = 'POST' action = "{{url_for('ChangeForgotPassword', token = token)}}" style = 'width:45%; margin-left: 27%;'>
      <div class = 'fields'>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class = 'title' style = 'padding: 1px;'>
          <p>Change Forgot Password</p>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.NewPassword.label}}
          </div>
          <div class = 'col-b'>
            {{form.NewPassword}}
          </div>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.ConfirmNewPassword.label}}
          </div>
          <div class = 'col-b'>
            {{form.ConfirmNewPassword}}
          </div>
        </div>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' class = 'btn-active' value = 'Submit'/>
        <a href = "{{url_for('login')}}">Back to Login</a>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                <div class = "{{category}}">
                <p>{{ message }}</p>
                </div>
              {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
    </form>
  </body>
</html>

enterprise_pmg/templates/LoginTemplates/forgot_password.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_login.css')}}" />
    <link rel="icon" href = "{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" /> 
  </head>
  <body>
    <form method = 'POST' action = "{{url_for('ForgotPassword')}}">
      <div class = 'fields'>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class = 'title' style = 'padding: 1px;'>
          <p>Forgot Password</p>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.email.label}}
          </div>
          <div class = 'col-b'>
            {{form.email}}
          </div>
        </div>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' class = 'btn-active' value = 'Submit'/>
        <a href = "{{url_for('login')}}">Back to Login</a>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                <div class = "{{category}}">
                <p>{{ message }}</p>
                </div>
              {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
    </form>
  </body>
</html>

enterprise_pmg/templates/LoginTemplates/home.html
{% extends 'LoginTemplates/layout.html'%}
{% block content%}
<div class = 'home-image-placeholder' >
    <img src = "{{url_for('static', filename = 'images/PM_Wallpaper.jpg')}}" class = 'home-image'/>
</div>
{% endblock %}

enterprise_pmg/templates/LoginTemplates/invalid_token.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_login.css')}}" />
    <link rel="icon" href = "{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" /> 
  </head>
  <body>
    <div class = 'message'>
        <img src = "{{url_for('static', filename = 'images/alert.png')}}" style = 'height:75px; width: 75px; float: left; margin: 10px;' />
        <p>The reset password token has expired. Please request another token by submitting your email at the 'Forgot Password' page.</p>
    </div>
  </body>
  <style>
      .message{
        background-color: rgba(0,0,0,0.3);
  border-style: solid;
  border-color: rgb(225,225,225);
  border-width: 1px;
  border-radius: 15px;
  color: red;
  width: 25%;
  margin-left: 35%;
  margin-top: 10%;
  padding: 15px;
  box-shadow: 5px 10px 20px rgb(0,0,35);
      }
  </style>
</html>

enterprise_pmg/templates/LoginTemplates/layout.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_main.css')}}"/>
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/jquery.treetable.css')}}"/>
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'js/jquery/dropzone-5.7.0/dist/dropzone.css')}}" />
    <link rel="icon" href="{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" />
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.min.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery-ui.min.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/search-box.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dropzone-5.7.0/dist/dropzone.js')}}"></script>
  </head>
  <body>
    <nav class = "main-nav">
      <ul>
        <li><a href = "{{url_for('home')}}">Home</a></li>
        {% if  'Admin' in role  or 'root' in role%}
        <li><a href = "{{url_for('admin.admin')}}">Administration</a></li>
        {% endif %}
        {% if 'Projects' in role or 'Tasks' in role or 'Budget' in role or 'root' in role%}
        <li><a href = "{{url_for('projects.allprojects')}}">Projects</a></li>
        {% endif %}
        <li class="dropdown">
          <img class = 'small-circle account-img' src = "{{image_file}}" />
          <a href ="javascript:void(0)" class="dropbtn"> {{username}}</a>
          <div class="dropdown-content">
            <a href="{{url_for('profile.UserProfile', uname = username)}}">View Profile</a>
            <a href="{{url_for('logout')}}">Log Out</a>
          </div>
        </li>
      </ul>
    </nav>

    <div class = 'mainpage'>
    {% block content %}
    {% endblock%}
    </div>
  </body>
</html>

enterprise_pmg/templates/LoginTemplates/login.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_login.css')}}" />
    <link rel="icon" href = "{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" /> 
  </head>
  <body>
    <form method = 'POST' action = "{{url_for('login')}}">
      <div class = 'fields'>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class = 'title'>
          <h2>Enterprise</h2>
          <h5>for Project Management</h5>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.usrname.label}}
          </div>
          <div class = 'col-b'>
            {{form.usrname}}
          </div>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.passwd.label}}
          </div>
          <div class = 'col-b'>
            {{form.passwd}}
          </div>
        </div>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' class = 'btn-active' value = 'Login'/>
        <a href = "{{url_for('ForgotPassword')}}">Forgot Password</a>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                <div class = "{{category}}">
                <p>{{ message }}</p>
                </div>
              {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
    </form>
  </body>
</html>

enterprise_pmg/templates/LoginTemplates/tester.html
<html>
  <head>
    <title>Testig Page</title>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.min.js')}}"></script>
  </head>
  <body>
    <form>
      <div class = 'fields'>
        <input type = 'text' name = 'fuckit' />
        <a href = "#" id = 'adder'>Add Line</a>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' value = 'Submit'/>
      </div>
    </form>
  </body>
  <script>
    $(document).ready(function(){
      var i = 1;
      $('#adder').click(function(){
        i++;
        $('.fields').append("<div class = 'added' id = 'div_"+i+"'><input type = 'text' name = 'fuckit' /><a href = '#' class = 'rmv' id = '"+i+"'>remove</a></div>");
      });

      $(document).on('click', '.rmv', function(){
        var ids = $(this).attr('id');
        $('#div_'+ ids).remove();
      });
    });
  </script>
</html>